### ISSUE TITLE
Module `sc4` not listed as dependency

### ISSUE THREAD

**Issue by Zasco** [sebamarynissen/sc4pac-helpers#1]
https://github.com/sebamarynissen/sc4pac-helpers/blob/83529db4e1d2ae5989fe7a841341395e38591856/package.json#L23-L30
Imported here:
https://github.com/sebamarynissen/sc4pac-helpers/blob/83529db4e1d2ae5989fe7a841341395e38591856/lib/dependency-tracker.js#L8-L10

**Comment by Zasco** [comment]
When I install it through **NPM** however, I don't get a missing module error anymore when running [`lib/dependency-tracker.js`](https://github.com/sebamarynissen/sc4pac-helpers/blob/main/lib/dependency-tracker.js), but this when running [`lib/cli.js`](https://github.com/sebamarynissen/sc4pac-helpers/blob/main/lib/cli.js):
```
V Fetching https://community.simtropolis.com/files/file/36565-ny-diagonal-midris
e-growify-set/
file:///*/sc4pac-helpers/
lib/scrape-st.js:32
                .previousElementSibling
                ^

TypeError: Cannot read properties of undefined (reading 'previousElementSibling'
)
    at parse (file:///*/s
c4pac-helpers/lib/scrape-st.js:32:3)
    at scrape (file:///*/
sc4pac-helpers/lib/scrape-st.js:226:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:
5)
    at async scrape (file:///*/sc4pac-helpers/lib/scrape.js:11:10)
    at async file:///*/sc
4pac-helpers/lib/cli.js:13:16

Node.js v23.2.0
```

**Comment by sebamarynissen** [comment]
Yeah that's because I linked the sc4 module with `npm link sc4`. Not sure what your experience with Node.js is, but basically it means that the sc4 module gets symlinked into node_modules, so that changes I make in the codebase there are instantly available here. That allows me to make changes in the sc4 module needed for my helper scripts without the need to publish a new version all the time.

I would suggest cloning the main branch of my sc4 module somewhere, and then running `npm link` in that repo, after which you can make it available in the helpers repo with `npm link sc4`. For more info, see https://docs.npmjs.com/cli/v9/commands/npm-link

**Comment by Zasco** [comment]
> Yeah that's because I linked the sc4 module with npm link sc4.

Haaa, get it.
> Not sure what your experience with Node.js is, but basically it means that the sc4 module gets symlinked into node_modules, so that changes I make in the codebase there are instantly available here.

Not much but good enough.
> That allows me to make changes in the sc4 module needed for my helper scripts without the need to publish a new version all the time.

I get it!
> I would suggest cloning the main branch of my sc4 module somewhere, and then running npm link in that repo, after which you can make it available in the helpers repo with npm link sc4.

I think I'll rather fork/branch and add **`sc4`** to dependencies.

**Comment by sebamarynissen** [comment]
That won't work because the changes I made - which my helpers rely on - are not published to npm yet. If you want it to work, make sure to install it as a dependency from Github instead:

```
npm install https://github.com/sebamarynissen/sc4#main
```

**Comment by sebamarynissen** [comment]
@Zasco I've published a new version of `sc4` to npm. It now includes all the needed functionality for the helpers - most notably the dependency tracking code. Hence I've added it as a an explicit dependency to package.json. So if you're forking this repo to play with it a bit, everything should now work.
