### ISSUE TITLE
`Cannot read properties of undefined (reading 'previousElementSibling' )`

### ISSUE THREAD

**Issue by Zasco** [sebamarynissen/sc4pac-helpers#2]
Getting this when running [`lib/cli.js`](https://github.com/sebamarynissen/sc4pac-helpers/blob/main/lib/cli.js):
```
V Fetching https://community.simtropolis.com/files/file/36565-ny-diagonal-midris
e-growify-set/
file:///*/sc4pac-helpers/
lib/scrape-st.js:32
                .previousElementSibling
                ^

TypeError: Cannot read properties of undefined (reading 'previousElementSibling'
)
    at parse (file:///*/s
c4pac-helpers/lib/scrape-st.js:32:3)
    at scrape (file:///*/
sc4pac-helpers/lib/scrape-st.js:226:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:
5)
    at async scrape (file:///*/sc4pac-helpers/lib/scrape.js:11:10)
    at async file:///*/sc
4pac-helpers/lib/cli.js:13:16

Node.js v23.2.0
```
Got it to work a few times however...

**Comment by Zasco** [comment]
Never mind, realised the site was under maintenance. -_-

**Comment by sebamarynissen** [comment]
That explains it 😅 nevertheless I'll have a look and see if I can provide an error message in that case. Do you know if the site returns a specific http code when under maintenance?

**Comment by Zasco** [comment]
> I'll have a look and see if I can provide an error message in that case.

Don't worry, I understand this is privately used code made public. Should I reopen/rename this issue accordingly?
> Do you know if the site returns a specific http code when under maintenance?

I wasn't sharp enough to think about saving the response... _ST_ admins must be able to provide it.

**Comment by sebamarynissen** [comment]
Bingo, ST is down again and it nicely returns an HTTP 503.
